"""Comprehensive market-map universes (not all are live-streamed)."""

from __future__ import annotations

# Liquid US equities for market map (Yahoo tickers == public symbols).
STOCK_CATALOG: tuple[tuple[str, str], ...] = (
    ("AAPL", "Apple Inc."),
    ("MSFT", "Microsoft Corporation"),
    ("GOOGL", "Alphabet Inc."),
    ("AMZN", "Amazon.com Inc."),
    ("NVDA", "NVIDIA Corporation"),
    ("META", "Meta Platforms Inc."),
    ("TSLA", "Tesla Inc."),
    ("BRK-B", "Berkshire Hathaway Inc."),
    ("AVGO", "Broadcom Inc."),
    ("JPM", "JPMorgan Chase & Co."),
    ("V", "Visa Inc."),
    ("MA", "Mastercard Inc."),
    ("LLY", "Eli Lilly and Company"),
    ("JNJ", "Johnson & Johnson"),
    ("WMT", "Walmart Inc."),
    ("XOM", "Exxon Mobil Corporation"),
    ("UNH", "UnitedHealth Group Inc."),
    ("HD", "The Home Depot Inc."),
    ("PG", "Procter & Gamble Co."),
    ("COST", "Costco Wholesale Corporation"),
    ("NFLX", "Netflix Inc."),
    ("AMD", "Advanced Micro Devices Inc."),
    ("CRM", "Salesforce Inc."),
    ("ORCL", "Oracle Corporation"),
    ("BAC", "Bank of America Corporation"),
    ("KO", "The Coca-Cola Company"),
    ("PEP", "PepsiCo Inc."),
    ("DIS", "The Walt Disney Company"),
    ("INTC", "Intel Corporation"),
    ("CSCO", "Cisco Systems Inc."),
    ("ADBE", "Adobe Inc."),
    ("QCOM", "QUALCOMM Inc."),
    ("MRK", "Merck & Co. Inc."),
    ("ABBV", "AbbVie Inc."),
    ("CVX", "Chevron Corporation"),
    ("TMO", "Thermo Fisher Scientific Inc."),
    ("ACN", "Accenture plc"),
    ("MCD", "McDonald's Corporation"),
    ("CSX", "CSX Corporation"),
    ("IBM", "International Business Machines"),
    ("GE", "General Electric Company"),
    ("CAT", "Caterpillar Inc."),
    ("AXP", "American Express Company"),
    ("TXN", "Texas Instruments Inc."),
    ("AMAT", "Applied Materials Inc."),
    ("NOW", "ServiceNow Inc."),
    ("ISRG", "Intuitive Surgical Inc."),
    ("UBER", "Uber Technologies Inc."),
    ("BKNG", "Booking Holdings Inc."),
    ("PFE", "Pfizer Inc."),
    ("T", "AT&T Inc."),
    ("VZ", "Verizon Communications Inc."),
    ("CMCSA", "Comcast Corporation"),
    ("NKE", "NIKE Inc."),
    ("BA", "The Boeing Company"),
    ("SPGI", "S&P Global Inc."),
    ("BLK", "BlackRock Inc."),
    ("MS", "Morgan Stanley"),
    ("GS", "Goldman Sachs Group Inc."),
    ("SCHW", "Charles Schwab Corporation"),
    ("C", "Citigroup Inc."),
    ("WFC", "Wells Fargo & Company"),
    ("LOW", "Lowe's Companies Inc."),
    ("SBUX", "Starbucks Corporation"),
    ("MDT", "Medtronic plc"),
    ("GILD", "Gilead Sciences Inc."),
    ("AMGN", "Amgen Inc."),
    ("BMY", "Bristol-Myers Squibb Company"),
    ("HON", "Honeywell International Inc."),
    ("UNP", "Union Pacific Corporation"),
    ("RTX", "RTX Corporation"),
    ("DE", "Deere & Company"),
    ("LMT", "Lockheed Martin Corporation"),
    ("PLD", "Prologis Inc."),
    ("ADI", "Analog Devices Inc."),
    ("PANW", "Palo Alto Networks Inc."),
    ("INTU", "Intuit Inc."),
    ("MU", "Micron Technology Inc."),
    ("LRCX", "Lam Research Corporation"),
    ("KLAC", "KLA Corporation"),
    ("SNPS", "Synopsys Inc."),
    ("CDNS", "Cadence Design Systems Inc."),
    ("REGN", "Regeneron Pharmaceuticals Inc."),
    ("VRTX", "Vertex Pharmaceuticals Inc."),
    ("ADP", "Automatic Data Processing Inc."),
    ("FI", "Fiserv Inc."),
    ("SYK", "Stryker Corporation"),
    ("TJX", "TJX Companies Inc."),
    ("MMC", "Marsh & McLennan Companies"),
    ("CB", "Chubb Limited"),
    ("SO", "Southern Company"),
    ("DUK", "Duke Energy Corporation"),
    ("NEE", "NextEra Energy Inc."),
    ("DHR", "Danaher Corporation"),
    ("ELV", "Elevance Health Inc."),
    ("CI", "The Cigna Group"),
    ("EQIX", "Equinix Inc."),
    ("SHW", "Sherwin-Williams Company"),
    ("MO", "Altria Group Inc."),
    ("PM", "Philip Morris International"),
    ("BX", "Blackstone Inc."),
    ("KKR", "KKR & Co. Inc."),
    ("APO", "Apollo Global Management"),
    ("COIN", "Coinbase Global Inc."),
    ("SHOP", "Shopify Inc."),
    ("SQ", "Block Inc."),
    ("PYPL", "PayPal Holdings Inc."),
    ("ABNB", "Airbnb Inc."),
    ("SNOW", "Snowflake Inc."),
    ("CRWD", "CrowdStrike Holdings Inc."),
    ("NET", "Cloudflare Inc."),
    ("DDOG", "Datadog Inc."),
    ("ZM", "Zoom Communications Inc."),
    ("ROKU", "Roku Inc."),
    ("RIVN", "Rivian Automotive Inc."),
    ("LCID", "Lucid Group Inc."),
    ("PLTR", "Palantir Technologies Inc."),
    ("ARM", "Arm Holdings plc"),
    ("SMCI", "Super Micro Computer Inc."),
    ("MAR", "Marriott International Inc."),
    ("HLT", "Hilton Worldwide Holdings"),
    ("GM", "General Motors Company"),
    ("F", "Ford Motor Company"),
    ("DAL", "Delta Air Lines Inc."),
    ("UAL", "United Airlines Holdings"),
    ("AAL", "American Airlines Group"),
)

# Top crypto universe for market map (Yahoo uses SYMBOL-USD).
CRYPTO_CATALOG: tuple[tuple[str, str], ...] = (
    ("BTC-USD", "Bitcoin"),
    ("ETH-USD", "Ethereum"),
    ("USDT-USD", "Tether"),
    ("BNB-USD", "BNB"),
    ("XRP-USD", "XRP"),
    ("SOL-USD", "Solana"),
    ("USDC-USD", "USD Coin"),
    ("DOGE-USD", "Dogecoin"),
    ("ADA-USD", "Cardano"),
    ("TRX-USD", "TRON"),
    ("AVAX-USD", "Avalanche"),
    ("LINK-USD", "Chainlink"),
    ("DOT-USD", "Polkadot"),
    ("TON-USD", "Toncoin"),
    ("SHIB-USD", "Shiba Inu"),
    ("BCH-USD", "Bitcoin Cash"),
    ("LTC-USD", "Litecoin"),
    ("NEAR-USD", "NEAR Protocol"),
    ("UNI-USD", "Uniswap"),
    ("APT-USD", "Aptos"),
    ("ICP-USD", "Internet Computer"),
    ("POL-USD", "Polygon"),
    ("ATOM-USD", "Cosmos"),
    ("ETC-USD", "Ethereum Classic"),
    ("XLM-USD", "Stellar"),
    ("FIL-USD", "Filecoin"),
    ("HBAR-USD", "Hedera"),
    ("ARB-USD", "Arbitrum"),
    ("OP-USD", "Optimism"),
    ("VET-USD", "VeChain"),
    ("IMX-USD", "Immutable"),
    ("INJ-USD", "Injective"),
    ("SUI-USD", "Sui"),
    ("SEI-USD", "Sei"),
    ("TIA-USD", "Celestia"),
    ("RENDER-USD", "Render"),
    ("FET-USD", "Artificial Superintelligence Alliance"),
    ("AAVE-USD", "Aave"),
    ("MKR-USD", "Maker"),
    ("GRT-USD", "The Graph"),
    ("ALGO-USD", "Algorand"),
    ("XTZ-USD", "Tezos"),
    ("EOS-USD", "EOS"),
    ("FLOW-USD", "Flow"),
    ("SAND-USD", "The Sandbox"),
    ("MANA-USD", "Decentraland"),
    ("AXS-USD", "Axie Infinity"),
    ("THETA-USD", "Theta Network"),
    ("EGLD-USD", "MultiversX"),
    ("FTM-USD", "Fantom"),
    ("RUNE-USD", "THORChain"),
    ("PEPE-USD", "Pepe"),
    ("WIF-USD", "dogwifhat"),
    ("BONK-USD", "Bonk"),
    ("FLOKI-USD", "FLOKI"),
    ("STX-USD", "Stacks"),
    ("KAS-USD", "Kaspa"),
    ("TAO-USD", "Bittensor"),
    ("WLD-USD", "Worldcoin"),
    ("JUP-USD", "Jupiter"),
    ("PYTH-USD", "Pyth Network"),
)
